### ISSUE TITLE
Doesn't work with GOG.com version of the game

### ISSUE THREAD

**Issue by DarkPreacher** [gemforce-team/BezelModLoader#7]
Title says it all, version of the game is 1.1.2b, but patch couldn't be applied. `courgette.log` file is empty.

**Comment by piepie62** [comment]
So, I think the in-progress Lattice branch might solve this problem. One thing I didn't think of, though, is the installer. It currently hardcodes it to the Steam data directory, but I think I might have found a way to fix that. I cannot test installation or usage for it; I do not own the GOG version. Would you be willing to test for me?

**Comment by DarkPreacher** [comment]
Sure, not a problem. Tell me what to do, and it will be done.

**Comment by piepie62** [comment]
Alrighty, I have a one thing I'd like you to do first for safety. Could you navigate to your save directory (probably `%APPDATA%/GCFW`, `%APPDATA%/com.giab.games.gcfw.gog`, or something similar) and copy the folder there, pasting it somewhere safe? It *shouldn't* be possible for this to break saves, but I'd rather be safe than sorry.
Once you've done that, the second step: extract this executable into your GCFW install folder (the one the old installer would have been run in) and double-click it. If an error pops up, please report it, otherwise try running GCFW.
When you run GCFW, it will either boot correctly (using a snapshot build of Bezel) or exit fairly instantly. If it exits fairly instantly, please send the Bezel log file, located at `<your save folder>/Local Store/Bezel Mod Loader/Bezel_log.log`. If it does not, that means Bezel was installed correctly. 
For safety's sake, this ZIP's SHA256 sum is d052ad651eb5c362dce92b4132f4afbd10858739aaa79c38c57a72aa20d2cd4b.
[bezel-installer.zip](https://github.com/gemforce-team/BezelModLoader/files/5641196/bezel-installer.zip)

In the case that this does not work, I will attempt to make the patches applied work with the GOG version. In the meantime, you can remove the .bkp from `<game folder>/META-INF/AIR/application.xml.bkp`, overwriting `application.xml`. This will

**Comment by DarkPreacher** [comment]
Yes, it works, thank you! I can see Bezel v0.2.1 next to changelog in game.

 <details>
  <summary>Bezel_log.log, just in case</summary>
<pre>
2020-12-04 11:07:43	[Bezel               ]: Bezel Mod Loader v0.2.1 for 1.1.2b
2020-12-04 11:07:43	[Lattice             ]: Loading previous coremod info
2020-12-04 11:07:44	[Bezel               ]: Loaded mod: ManaMason v1.4
2020-12-04 11:07:44	[Bezel               ]: Loaded mod: Gemsmith v1.11
2020-12-04 11:07:44	[Bezel               ]: Loaded mod: Autocast v1.1
2020-12-04 11:07:51	[Bezel               ]: Bezel bound to game's objects!
2020-12-04 11:07:51	[ManaMason           ]: Found 1 blueprint files.
2020-12-04 11:07:51	[ManaMason           ]: ManaMason initialized!
2020-12-04 11:07:51	[Bezel               ]: Bound mod: ManaMason
2020-12-04 11:07:51	[Gemsmith            ]: Found 1 recipe files.
2020-12-04 11:07:51	[Gemsmith            ]: Loaded existing configuration
2020-12-04 11:07:51	[Gemsmith            ]: Mod version: v1.11 for 1.1.2b
2020-12-04 11:07:51	[Gemsmith            ]: Checking for updates...
2020-12-04 11:07:51	[Gemsmith            ]: Gemsmith initialized!
2020-12-04 11:07:51	[Bezel               ]: Bound mod: Gemsmith
2020-12-04 11:07:51	[Autocast            ]: Autocast initialized!
2020-12-04 11:07:51	[Bezel               ]: Bound mod: Autocast
2020-12-04 11:07:52	[Gemsmith            ]: Using the latest version: v1.11-for-1.1.2b
</pre>
</details>

**Comment by piepie62** [comment]
Cool! No more changes need to be made for GOG support, then. Always nice when that happens. I'll PR those changes to this repository now

**Comment by DarkPreacher** [comment]
Nice, thank you once again. Will close issue now.

**Comment by DesertBoss** [comment]
If the error "BytecodeEditor could not be found" appears when starting the game, here is the solution:
1) Open the file in the game directory along the path "\META-INF\AIR\application.xml".
2) In the first line remove "<extensionID>com.cff.anebe.ANEBytecodeEditor</extensionID>".
3) Before the line with "</application>" insert the line "<extensions><extensionID>com.cff.anebe.ANEBytecodeEditor</extensionID></extensions>".
4) Done.

**Comment by DesertBoss** [comment]
1) Open the file in the game directory along the path  `\META-INF\AIR\application.xml`
2) In the first line remove  `<extensionID>com.cff.anebe.ANEBytecodeEditor</extensionID>`
3) Before the line with  `</application>`  insert the line  `<extensions><extensionID>com.cff.anebe.ANEBytecodeEditor</extensionID></extensions>`
4) Done

**Comment by DesertBoss** [comment]
If the error `BytecodeEditor could not be found` occurs after launching the game, here is the solution:
1) Open the file in the game directory along the path  `\META-INF\AIR\application.xml`
2) In the first line remove  `<extensionID>com.cff.anebe.ANEBytecodeEditor</extensionID>`
3) Before the line with  `</application>`  insert the line  `<extensions><extensionID>com.cff.anebe.ANEBytecodeEditor</extensionID></extensions>`
4) Done
